export const musixmatchServiceStub = {
  getTrackList: [
    {
      page: '49',
      track_id: 11,
      track_name: 'track_name_01',
      artist_id: 110,
      artist_name: 'artist_name_01',
      played: 0,
      snippet: '',
    },
    {
      page: '49',
      track_id: 12,
      track_name: 'track_name_02',
      artist_id: 120,
      artist_name: 'artist_name_02',
      played: 0,
      snippet: '',
    },
    {
      page: '49',
      track_id: 13,
      track_name: 'track_name_03',
      artist_id: 130,
      artist_name: 'artist_name_03',
      played: 0,
      snippet: '',
    },
    {
      page: '49',
      track_id: 14,
      track_name: 'track_name_04',
      artist_id: 140,
      artist_name: 'artist_name_04',
      played: 0,
      snippet: '',
    },
    {
      page: '49',
      track_id: 15,
      track_name: 'track_name_05',
      artist_id: 150,
      artist_name: 'artist_name_05',
      played: 0,
      snippet: '',
    },
  ],
  getSnippetByTrackId: { snippet_body: 'But I hope they live forever' },
  getRelatedArtistList: [
    {
      artist_id: 24749475,
      artist_name: 'Metro Karaoke',
      related_artist_names: [],
    },
    {
      artist_id: 24775660,
      artist_name: 'Variété Française',
      related_artist_names: [],
    },
    {
      artist_id: 24834244,
      artist_name: 'Karaoke 365',
      related_artist_names: [],
    },
    {
      artist_id: 25765679,
      artist_name: '2010s Karaoke Band',
      related_artist_names: [],
    },
    {
      artist_id: 25915181,
      artist_name: 'Cover Pop',
      related_artist_names: [],
    },
  ],
}
